---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd

platforms:
  - name: debian-10
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install udev git -y
  - name: debian-9
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install udev git -y
  - name: centos-7
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - yum install udev systemd-sysv libicu git -y
  - name: ubuntu-16.04
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install udev git -y

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: bareos
  pillars:
    top.sls:
      base:
        '*':
          - bareos
    bareos.sls:
      bareos:
        use_upstream_repo: true
        director:
          database:
            manage: true

verifier:
  name: inspec
  sudo: true

suites:
  - name: bareos-postgresql
    provisioner:
      dependencies:
        - name: postgres
          repo: git
          source: https://github.com/saltstack-formulas/postgres-formula.git
      pillars-from-files:
        bareos.sls: test/integration/bareos-postgresql/bareos-postgresql.pillar.yaml
      state_top:
        base:
          '*':
            - postgres
            - bareos

  - name: bareos-mysql
    provisioner:
      dependencies:
        - name: mysql
          repo: git
          source: https://github.com/saltstack-formulas/mysql-formula.git
      pillars:
        bareos.sls:
          mysql:
            server:
              root_password: ''
          bareos:
            director:
              database:
                backend: mysql
      state_top:
        base:
          '*':
            - mysql
            - bareos
